// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace GTD.Migrations
{
    public sealed partial class taskdeleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(taskdeleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201505310203220_taskdeleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
