// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace GTD.Migrations
{
    public sealed partial class addnexttaskid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnexttaskid));
        
        string IMigrationMetadata.Id
        {
            get { return "201505151309136_addnexttaskid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
