// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace GTD.Migrations
{
    public sealed partial class addnexttask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnexttask));
        
        string IMigrationMetadata.Id
        {
            get { return "201505151224591_addnexttask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
